package CarpoolLang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class AppRender_SubstituteMenu extends SubstituteMenuBase {
  public AppRender_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for AppRender. Generated from implicit smart reference attribute.", new SNodePointer("r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)", "7076342757639698321")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_3zy4e8_a(), CONCEPTS.AppRender$br));
    result.add(new SMP_Subconcepts_3zy4e8_b());
    return result;
  }

  public class SMP_ReferenceScope_3zy4e8_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_3zy4e8_a() {
      super(CONCEPTS.AppRender$br, LINKS.componentName$1j5l, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_3zy4e8_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_3zy4e8_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "AppRender", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.AppRender$br);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AppRender$br = MetaAdapterFactory.getConcept(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x6234383efa05b791L, "CarpoolLang.structure.AppRender");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink componentName$1j5l = MetaAdapterFactory.getReferenceLink(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x6234383efa05b791L, 0x6234383efa05b794L, "componentName");
  }
}
