import type { Metadata } from "next";

import AppNavbar from "@/components/app-navbar";
import Navbar from "@/components/navbar";
import Providers from "@/components/providers";
import SessionWrapper from "@/components/session-wrapper";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

export const metadata: Metadata = {
  title: "Carpool",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <SessionWrapper>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          themes={["light", "dark", "green", "darkGreen"]}
          disableTransitionOnChange
        > */}
        <body className="h-screen w-screen">
          <Providers>
            <AppNavbar />
            <main className="flex-grow">{children}</main>
            <Toaster />
          </Providers>
          {/* <Sidebar /> */}
          <Navbar />
        </body>
        {/* </ThemeProvider> */}
      </SessionWrapper>
    </html>
  );
}
