package CarpoolLang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class RenderTabs_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.list$JMcm)) {
      tgs.appendNode(item);
    }
    tgs.indent();
    tgs.append("</TabsList>\n");
    for (SNode l : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.list$JMcm))) {
      for (SNode row : ListSequence.fromList(SLinkOperations.getChildren(l, LINKS.rows$Kgfk))) {
        if (SPropertyOperations.hasValue(row, PROPS.value$KgIk, "cars")) {
          tgs.indent();
          tgs.append("<TabsContent value=\"");
          tgs.append(SPropertyOperations.getString(row, PROPS.value$KgIk));
          tgs.append("\">\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<Card className=\"p-6\">\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<div className=\"mb-6 flex items-center justify-between\">\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<h2 className=\"flex items-center gap-2 text-xl font-semibold\">\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<Car className=\"h-5 w-5\" />\n");
          tgs.indent();
          tgs.append(SPropertyOperations.getString(row, PROPS.label$KgXl));
          tgs.append("\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</h2>\n");
          tgs.indent();
          tgs.append("<Link href=\"/add-car\">\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<Button>\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<Car className=\"mr-2 h-4 w-4\" />\n");
          tgs.indent();
          tgs.append("Add new car\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</Button>\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</Link>\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</div>\n");
          tgs.indent();
          tgs.append("<UserCars userId={session?.user.id} />\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</Card>\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</TabsContent>\n");
        }
        if (SPropertyOperations.hasValue(row, PROPS.value$KgIk, "rides")) {
          tgs.indent();
          tgs.append("<TabsContent value=\"");
          tgs.append(SPropertyOperations.getString(row, PROPS.value$KgIk));
          tgs.append("\">\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<Card className=\"p-6\">\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<div className=\"mb-6 flex items-center justify-between\">\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<h2 className=\"flex items-center gap-2 text-xl font-semibold\">\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<Car className=\"h-5 w-5\" />\n");
          tgs.indent();
          tgs.append(SPropertyOperations.getString(row, PROPS.label$KgXl));
          tgs.append("\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</h2>\n");
          tgs.indent();
          tgs.append("<Link href=\"/find-ride\">\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<Button>\n");
          ctx.getBuffer().area().increaseIndent();
          tgs.indent();
          tgs.append("<Car className=\"mr-2 h-4 w-4\" />\n");
          tgs.indent();
          tgs.append("Book a Ride\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</Button>\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</Link>\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</div>\n");
          tgs.indent();
          tgs.append("<UserCars userId={session?.user.id} />\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</Card>\n");
          ctx.getBuffer().area().decreaseIndent();
          tgs.indent();
          tgs.append("</TabsContent>\n");
        }

      }
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink list$JMcm = MetaAdapterFactory.getContainmentLink(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x62945a6b81827485L, 0x62945a6b81827489L, "list");
    /*package*/ static final SContainmentLink rows$Kgfk = MetaAdapterFactory.getContainmentLink(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x62945a6b81827487L, 0x62945a6b818274b5L, "rows");
  }

  private static final class PROPS {
    /*package*/ static final SProperty value$KgIk = MetaAdapterFactory.getProperty(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x62945a6b818274b1L, 0x62945a6b818274b3L, "value");
    /*package*/ static final SProperty label$KgXl = MetaAdapterFactory.getProperty(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x62945a6b818274b1L, 0x62945a6b818274b4L, "label");
  }
}
