package CarpoolLang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class TabsList_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (SNode tab : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.rows$Kgfk))) {
      tgs.indent();
      tgs.append("<TabsTrigger value=\"");
      tgs.append(SPropertyOperations.getString(tab, PROPS.value$KgIk));
      tgs.append("\">");
      tgs.append(SPropertyOperations.getString(tab, PROPS.label$KgXl));
      tgs.append("</TabsTrigger>\n");
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty value$KgIk = MetaAdapterFactory.getProperty(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x62945a6b818274b1L, 0x62945a6b818274b3L, "value");
    /*package*/ static final SProperty label$KgXl = MetaAdapterFactory.getProperty(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x62945a6b818274b1L, 0x62945a6b818274b4L, "label");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink rows$Kgfk = MetaAdapterFactory.getContainmentLink(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x62945a6b81827487L, 0x62945a6b818274b5L, "rows");
  }
}
