package CarpoolLang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import CarpoolLang.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.AppRender:
        return new AppRender_TextGen();
      case LanguageConceptSwitch.CarpoolNotation:
        return new CarpoolNotation_TextGen();
      case LanguageConceptSwitch.RenderTabs:
        return new RenderTabs_TextGen();
      case LanguageConceptSwitch.TabsList:
        return new TabsList_TextGen();
      case LanguageConceptSwitch.TabsListRow:
        return new TabsListRow_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.CarpoolNotation$f6)) {
        String fname = getFileName_CarpoolNotation(root);
        String ext = getFileExtension_CarpoolNotation(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_CarpoolNotation(SNode node) {
    return "App";
  }
  private static String getFileExtension_CarpoolNotation(SNode node) {
    return "tsx";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept CarpoolNotation$f6 = MetaAdapterFactory.getConcept(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x6234383ef9f9a3f7L, "CarpoolLang.structure.CarpoolNotation");
  }
}
