package CarpoolLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AppApiEndpoints;
  private ConceptPresentation props_AppComponents;
  private ConceptPresentation props_AppMenuItems;
  private ConceptPresentation props_AppRender;
  private ConceptPresentation props_Button;
  private ConceptPresentation props_ButtonIcon;
  private ConceptPresentation props_CarpoolNotation;
  private ConceptPresentation props_FormInput;
  private ConceptPresentation props_RenderForm;
  private ConceptPresentation props_RenderHeading;
  private ConceptPresentation props_RenderTable;
  private ConceptPresentation props_RenderText;
  private ConceptPresentation props_TableCell;
  private ConceptPresentation props_TableHeading;
  private ConceptPresentation props_TableRow;
  private ConceptPresentation props_TableTitle;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AppApiEndpoints:
        if (props_AppApiEndpoints == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_AppApiEndpoints = cpb.create();
        }
        return props_AppApiEndpoints;
      case LanguageConceptSwitch.AppComponents:
        if (props_AppComponents == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_AppComponents = cpb.create();
        }
        return props_AppComponents;
      case LanguageConceptSwitch.AppMenuItems:
        if (props_AppMenuItems == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_AppMenuItems = cpb.create();
        }
        return props_AppMenuItems;
      case LanguageConceptSwitch.AppRender:
        if (props_AppRender == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_AppRender = cpb.create();
        }
        return props_AppRender;
      case LanguageConceptSwitch.Button:
        if (props_Button == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Button = cpb.create();
        }
        return props_Button;
      case LanguageConceptSwitch.ButtonIcon:
        if (props_ButtonIcon == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ButtonIcon = cpb.create();
        }
        return props_ButtonIcon;
      case LanguageConceptSwitch.CarpoolNotation:
        if (props_CarpoolNotation == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_CarpoolNotation = cpb.create();
        }
        return props_CarpoolNotation;
      case LanguageConceptSwitch.FormInput:
        if (props_FormInput == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_FormInput = cpb.create();
        }
        return props_FormInput;
      case LanguageConceptSwitch.RenderForm:
        if (props_RenderForm == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RenderForm = cpb.create();
        }
        return props_RenderForm;
      case LanguageConceptSwitch.RenderHeading:
        if (props_RenderHeading == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RenderHeading = cpb.create();
        }
        return props_RenderHeading;
      case LanguageConceptSwitch.RenderTable:
        if (props_RenderTable == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RenderTable = cpb.create();
        }
        return props_RenderTable;
      case LanguageConceptSwitch.RenderText:
        if (props_RenderText == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RenderText = cpb.create();
        }
        return props_RenderText;
      case LanguageConceptSwitch.TableCell:
        if (props_TableCell == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_TableCell = cpb.create();
        }
        return props_TableCell;
      case LanguageConceptSwitch.TableHeading:
        if (props_TableHeading == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_TableHeading = cpb.create();
        }
        return props_TableHeading;
      case LanguageConceptSwitch.TableRow:
        if (props_TableRow == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_TableRow = cpb.create();
        }
        return props_TableRow;
      case LanguageConceptSwitch.TableTitle:
        if (props_TableTitle == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_TableTitle = cpb.create();
        }
        return props_TableTitle;
    }
    return null;
  }
}
