package CarpoolLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_HttpMethod extends EnumerationDescriptorBase {

  public EnumerationDescriptor_HttpMethod() {
    super(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x58d9188ac922ce14L, "HttpMethod", "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/6402175329642925588");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_GET_0 = new EnumerationDescriptor.MemberDescriptor("GET", "GET", 0x58d9188ac922ce15L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/6402175329642925589");
  private final EnumerationDescriptor.MemberDescriptor myMember_POST_0 = new EnumerationDescriptor.MemberDescriptor("POST", "POST", 0x58d9188ac922ce16L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/6402175329642925590");
  private final EnumerationDescriptor.MemberDescriptor myMember_PUT_0 = new EnumerationDescriptor.MemberDescriptor("PUT", "PUT", 0x58d9188ac922ce17L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/6402175329642925591");
  private final EnumerationDescriptor.MemberDescriptor myMember_DELETE_0 = new EnumerationDescriptor.MemberDescriptor("DELETE", "DELETE", 0x58d9188ac922ce18L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/6402175329642925592");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x58d9188ac922ce14L, 0x58d9188ac922ce15L, 0x58d9188ac922ce16L, 0x58d9188ac922ce17L, 0x58d9188ac922ce18L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_GET_0, myMember_POST_0, myMember_PUT_0, myMember_DELETE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_GET_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "GET":
        return myMember_GET_0;
      case "POST":
        return myMember_POST_0;
      case "PUT":
        return myMember_PUT_0;
      case "DELETE":
        return myMember_DELETE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
