package CarpoolLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_InputType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_InputType() {
    super(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x6234383efa10088fL, "InputType", "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/7076342757640374415");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Select_0 = new EnumerationDescriptor.MemberDescriptor("Select", "Select", 0x6234383efa100890L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/7076342757640374416");
  private final EnumerationDescriptor.MemberDescriptor myMember_Date_0 = new EnumerationDescriptor.MemberDescriptor("Date", "Date", 0x6234383efa100891L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/7076342757640374417");
  private final EnumerationDescriptor.MemberDescriptor myMember_Time_0 = new EnumerationDescriptor.MemberDescriptor("Time", "Time", 0x6234383efa100892L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/7076342757640374418");
  private final EnumerationDescriptor.MemberDescriptor myMember_Number_0 = new EnumerationDescriptor.MemberDescriptor("Number", "Number", 0x6234383efa100893L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/7076342757640374419");
  private final EnumerationDescriptor.MemberDescriptor myMember_TextArea_0 = new EnumerationDescriptor.MemberDescriptor("TextArea", "TextArea", 0x6234383efa100894L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/7076342757640374420");
  private final EnumerationDescriptor.MemberDescriptor myMember_Email_0 = new EnumerationDescriptor.MemberDescriptor("Email", "Email", 0x6234383efa100895L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/7076342757640374421");
  private final EnumerationDescriptor.MemberDescriptor myMember_Password_0 = new EnumerationDescriptor.MemberDescriptor("Password", "Password", 0x6234383efa100896L, "r:213b5080-9e54-4891-acb4-be7d245d7219(CarpoolLang.structure)/7076342757640374422");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x722e4ffa13ae440cL, 0xb33c3c19945a9c69L, 0x6234383efa10088fL, 0x6234383efa100890L, 0x6234383efa100891L, 0x6234383efa100892L, 0x6234383efa100893L, 0x6234383efa100894L, 0x6234383efa100895L, 0x6234383efa100896L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Select_0, myMember_Date_0, myMember_Time_0, myMember_Number_0, myMember_TextArea_0, myMember_Email_0, myMember_Password_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Select_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Select":
        return myMember_Select_0;
      case "Date":
        return myMember_Date_0;
      case "Time":
        return myMember_Time_0;
      case "Number":
        return myMember_Number_0;
      case "TextArea":
        return myMember_TextArea_0;
      case "Email":
        return myMember_Email_0;
      case "Password":
        return myMember_Password_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
