CarpoolNotation = AppName AppTitle AppDescription AppPort AppTheme AppMenuPosition AppMenuItems AppComponents AppApi AppRenders

AppName = "name:" appName
AppTitle = "title:" title
AppDescription = "description:" description
AppPort = "port:" port
AppTheme = "theme:" Theme
AppMenuPosition = "menu_position:" MenuPosition
AppMenuItems = "menu_items:" MenuItems
AppComponents = "components:" Components
AppApi = "api:" Api
AppRenders = "render:" Render

Theme = "light" | "dark" | "blue" | "orange" | "violet" | "useSystem"
MenuPosition = "top" | "right" | "left"
MenuItems = MenuItem+
MenuItem = "label:" label ',' "component:" componentName
Components = Component+
Component = "name:" componentName ',' "url:" url ',' "menu:" YesNo ',' "authentication:" YesNo
YesNo = "yes" | "no" 

Api = "base:" baseURL "endpoints:" Endpoint+
Endpoint = "name:" name ',' "url:" url ',' "method:" HttpMethod 
HttpMethod = "GET" | "POST" | "PUT" | "DELETE" 

Render = RenderSection+
RenderSection = name ':' Content+  

Content = Text | Image | Form | Card | Link | Table | Button

Text = ("#"+)? text | "**" text "**" | text
Image = "{img:" url ',' "alt=" altText ',' "style=align:" Align ';' "}" 
Align = "left" | "center" | "right" 
Card = "//Card//" "Title:" cardTitle, "Content:" CardStyle* CardContent+ 
CardStyle = "style=space:even"
CardContent = (Text '|')+ Link Button*
Form = "//Form//" FormField+ Button 
FormField = Text "[Input " InputType (', min: ' minValue (', max:' maxValue)?)? "]"
InputType = "Text" | "Date" | "Number" | "Textarea" | "Email" | "Password" 
Link = "[" label "|" url (',' "style=text:right")? "]" 
Button = "[[" label "|" url (',' Icon)? "]]"
Icon = "icon:" iconName
Table = TableHeader TableRow+
TableHeader = ("|" Text "|")+ ("|----------|")+
TableRow = "|" Text "|" | "|" Button* "|" | "{{"  "}}"